# Except for the secret key, none of these are actually needed; Rocket has sane
# defaults. We show all of them here explicitly for demonstrative purposes.
[default]
template_dir = "web"

[global.limits]
forms = 32768
graphql = 131072
json = 1048576 # this is an extra used by the json contrib module
msgpack = 1048576 # this is an extra used by the msgpack contrib module

[debug]
address = "127.0.0.1"
port = 8000
workers = 1
keep_alive = 5
log = "normal"
template_dir = "web"

[staging]
address = "127.0.0.1"
port = 8000
workers = 8
keep_alive = 5
log = "normal"
template_dir = "web"

[release]
address = "127.0.0.1"
port = 8000
workers = 12
keep_alive = 5
log = "critical"
template_dir = "web"