[package]
name = "mbp2-backend"
version = "0.3.2"
edition = "2021"
build = "build.rs"
publish = false

[[bin]]
name = "mbp2_backend"
path = "index.rs"

[dependencies]
bson = { version = "2.6.1", features = ["chrono-0_4"] }
chrono = "0.4.26"
common_macros = "0.1.1"
dotenv = "0.15.0"
figment = { version = "0.10.10", features = ["env", "json", "serde_yaml", "toml", "yaml"] }
futures = { version = "0.3.28", features = ["compat"] }
futures-macro = "0.3.28"
handlebars = { version = "4.3.7", features = ["dir_source"] }
lazy_static = "1.4.0"
mbp2 = { path="../../", version="*", features=["async-gql", "crypto"], default-features=false }
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
tokio = { version = "1.29.1", features = ["full"] }
ulid = { version = "1.0.0", features = ["serde"] }

[dependencies.mongodb]
version = "2.6.0"
default-features = false
features = ["tokio-sync", "tokio-runtime"]

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
branch = "master"
version = "^0.5.0-rc.2"
features = [ "json", "tls" ]

[dependencies.rocket_dyn_templates]
git = "https://github.com/SergioBenitez/Rocket"
branch = "master"
version = "^0.1.0-rc.2"
features = [ "handlebars" ]

[dependencies.async-graphql]
git = "https://github.com/async-graphql/async-graphql"
branch = "master"
version = "^6.0"
features = [
   "apollo_tracing", "apollo_persisted_queries",
   "bson", "dynamic-schema", "graphiql", "log",
   "playground", "opentelemetry", "tracing"
]

[build-dependencies]
fs_extra = "1.3.0"
