[package]
name = "mbp2-app"
version = "0.3.0"
edition = "2021"

[[bin]]
name = "mbp2-app"
path = "index.rs"

[dependencies]
mbp2 = { path="../../", version="*" }
tokio = { version = "1.23.0", features = ["full"] }
dotenv = "0.15.0"
rocket_contrib = "0.4.11"
lazy_static = "1.4.0"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
branch = "v0.5-rc"
version = "^0.5.0-rc.2"
features = [ "tls" ]
